# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_date',
        ),
    ]
