# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-28 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0003_order_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.CharField(default='unknown', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
