# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 21:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sky', '0004_auto_20170428_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sky.Client'),
            preserve_default=False,
        ),
    ]
